### PR TITLE
Upgrade to MkDocs Material 5

### LINKED ISSUE #10: Docs browser compatability issue: logo reloading
Screen-Recording-2020-02-17-at-1

I know browser compatability is boring, but on Firefox the logo gets removed and re-loaded on each click of the top nav, as demonstrated by this screen recording (the GIF converter  I used dropped several frames so it looks like the reloading didn't happen for the middle item, but it did).

This actually isn't just the top nav, it happens when clicking on anything in the left-hand nav bar too.

Works as expected on Chromium.

_Originally posted by @AdamHillier in https://github.com/larq/larq/pull/418#issuecomment-587046444_

This was a comment on the PR linked above, so the recording is of a preview of the new docs site, but the issue also arises with the existing site.

### PR DESCRIPTION
**Pull request by lgeiger**
Closes #58 
Closes #56
Closes #10

## TODO
- [x] Upgrade yaml config
- [x] Bring back html customisations
- [x] Bring back social preview and other header metadata
- [x] Add larq colour scheme with [CSS variables](https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette) (@leonoverweel can you help me with this next week during our small docs hackathon?)
- [x] Fix overflow in notebook output

### CODE REVIEW

**Comment by lgeiger** [comment]
I enabled the new experimental instant loading feature of mkdocs-material with some small modifications to MathJax and Vega rendering in 0a943852f7a9a45509f4623e7a1117357a79c8e2. Now our docs will behave like a single-page app which is an overkill fix for #10 and will make  everything super fast 🚀

**Comment by AdamHillier** [comment]
> ... which is an overkill fix for #10 ...

Haha this does indeed fix #10, verified in Firefox 74.0.1 on MacOS.

**Comment by lgeiger** [comment]
The CSS colours are definitely not perfect, but I think it is now on par with current `master`.
This should be ready for a testdrive at https://docs-n3i444yap.now.sh/

@timdebruin Could you check if this fixes #32 for you?

**Comment by timdebruin** [comment]
> @timdebruin Could you check if this fixes #32 for you?

Fixed 👍

**Comment by leonoverweel** [comment]
> The CSS colours are definitely not perfect

I'll play with this during the docs hackathon tomorrow; don't think it's blocking for this PR.

**Comment by lgeiger** [comment]
> I'll play with this during the docs hackathon tomorrow; don't think it's blocking for this PR.

Thanks. `mkdocs-material` v5 now allows to define the colours with CSS variables (see [here](https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette))

**Comment by AdamHillier** [comment]
> Thanks. `mkdocs-material` v5 now allows to define the colours with CSS variables (see [here](https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette))

It actually surprises me that they use that feature, given it's not supported by ~7% of browsers currently in use: https://caniuse.com/#feat=css-variables.

I just tested and this new deployment indeed does not work in IE 11. I don't really think that's a huge problem, but it's something we should be aware of.

**Comment by lgeiger** [comment]
> It actually surprises me that they use that feature, given it's not supported by ~7% of browsers currently in use

For reference https://github.com/squidfunk/mkdocs-material/issues/1537

**Pull request merged**
